services:
  db:
    image: postgres:17
    container_name: db-production
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.production
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER']
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: ${BACKEND_IMAGE_TAG}
    container_name: backend-production
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
volumes:
  postgres-data:
