version: '3.9'

services:
  db:
    image: postgres:17
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME}']
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env.production

  backend:
    image: ${BACKEND_IMAGE_TAG}
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
volumes:
  postgres-data:
