name: Build & Deploy Backend to GCE

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Build Docker images
        run: |
          # Build Backend image
          docker build -t asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/slj-repo/backend:${{ github.sha }} .
          
          # Build DB image
          docker build -t asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/slj-repo/db:${{ github.sha }} -f Dockerfile.db .
          
          # Tag images as latest
          docker tag asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/slj-repo/backend:${{ github.sha }} asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/slj-repo/backend:latest
          docker tag asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/slj-repo/db:${{ github.sha }} asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/slj-repo/db:latest

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

      - name: Push images to Artifact Registry
        run: |
          # Push Backend images
          docker push asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/slj-repo/backend:${{ github.sha }}
          docker push asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/slj-repo/backend:latest
          
          # Push DB images
          docker push asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/slj-repo/db:${{ github.sha }}
          docker push asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/slj-repo/db:latest

      - name: Upload docker-compose.yml to GCE VM
        run: |
          gcloud compute scp docker-compose.yml ${{ secrets.GCE_USER }}@${{ secrets.GCE_INSTANCE_NAME }}:/home/${{ secrets.GCE_USER }}/backend/docker-compose.yml --zone=${{ secrets.GCE_INSTANCE_ZONE }}

      - name: Upload .env.production to GCE VM
        run: |
          echo "${{ secrets.BACKEND_ENV_PRODUCTION }}" > .env.production
          gcloud compute scp .env.production ${{ secrets.GCE_USER }}@${{ secrets.GCE_INSTANCE_NAME }}:/home/${{ secrets.GCE_USER }}/backend/.env.production --zone=${{ secrets.GCE_INSTANCE_ZONE }}

      - name: Deploy to GCE VM
        run: |
          gcloud compute ssh ${{ secrets.GCE_USER }}@${{ secrets.GCE_INSTANCE_NAME }} --zone=${{ secrets.GCE_INSTANCE_ZONE }} --command='
            set -e
            echo "Configuring Docker on VM..."
            gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet
            
            # กำหนด image tags สำหรับ backend และ db
            BACKEND_IMAGE="asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/slj-repo/backend:${{ github.sha }}"
            DB_IMAGE="asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/slj-repo/db:${{ github.sha }}"
            
            cd /home/${{ secrets.GCE_USER }}/backend
            echo "Pulling new images..."
            docker pull $BACKEND_IMAGE
            docker pull $DB_IMAGE

            echo "Loading env variables..."
            set -o allexport
            source .env.production
            set +o allexport

            echo "Starting Docker Compose..."
            export BACKEND_IMAGE_TAG=$BACKEND_IMAGE
            export DB_IMAGE_TAG=$DB_IMAGE
            
            # ตรวจสอบว่า containers กำลังทำงานอยู่หรือไม่
            if ! docker ps | grep -q "db-production" && ! docker ps | grep -q "backend-production"; then
              echo "Starting all services (database and backend)..."
              docker-compose -f docker-compose.yml up -d
            else
              if docker ps | grep -q "db-production"; then
                echo "Database already running, stopping before update..."
                docker-compose -f docker-compose.yml stop db
              fi
              echo "Updating services..."
              docker-compose -f docker-compose.yml up -d
            fi
            
            echo "Cleaning up old Docker images..."
            docker image prune -af --filter "until=24h" || true
            echo "Deployment successful!"
          '
